2018-08-27 06:00:01,487 DEBU root Last attempt: 2018-08-27T00:00:02Z
2018-08-27 06:00:01,487 DEBU root Last success: 2018-08-27T00:00:02Z
2018-08-27 06:00:01,487 INFO root Writing last-update file
2018-08-27 06:00:01,487 INFO root Query: 'collection:archivebot oai_updatedate:[2018-08-27T00:00:02Z TO null]'
2018-08-27 06:00:04,854 INFO root Processing item archiveteam_archivebot_go_20180827010002
2018-08-27 06:00:04,854 INFO root Skipping archiveteam_archivebot_go_20180827010002_archive.torrent
2018-08-27 06:00:04,855 INFO root Skipping archiveteam_archivebot_go_20180827010002_files.xml
2018-08-27 06:00:04,855 INFO root Skipping archiveteam_archivebot_go_20180827010002_meta.sqlite
2018-08-27 06:00:04,855 INFO root Skipping archiveteam_archivebot_go_20180827010002_meta.xml
2018-08-27 06:00:04,855 ERRO root Size of arhivach.cf-inf-20180803-012549-8guux-00162.warc.os.cdx.gz is missing
2018-08-27 06:00:04,855 ERRO root Mtime of arhivach.cf-inf-20180803-012549-8guux-00162.warc.os.cdx.gz is missing
2018-08-27 06:00:04,855 ERRO root Size of ateneotarsisrepublicana.blogspot.com-inf-20180827-034554-2xgln-00000.warc.os.cdx.gz is missing
2018-08-27 06:00:04,855 ERRO root Mtime of ateneotarsisrepublicana.blogspot.com-inf-20180827-034554-2xgln-00000.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Size of ateneotarsisrepublicana.blogspot.com-inf-20180827-034554-2xgln-meta.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Mtime of ateneotarsisrepublicana.blogspot.com-inf-20180827-034554-2xgln-meta.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Size of barrapunto.com-inf-20180610-140525-1oqct-00061.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Mtime of barrapunto.com-inf-20180610-140525-1oqct-00061.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Size of callahan.mysite.com-inf-20180825-063247-42d1e-00000.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Mtime of callahan.mysite.com-inf-20180825-063247-42d1e-00000.warc.os.cdx.gz is missing
2018-08-27 06:00:04,856 ERRO root Size of ingaza.wordpress.com-inf-20180826-150831-1t4u9-00000.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Mtime of ingaza.wordpress.com-inf-20180826-150831-1t4u9-00000.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Size of ingaza.wordpress.com-inf-20180826-150831-1t4u9-00001.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Mtime of ingaza.wordpress.com-inf-20180826-150831-1t4u9-00001.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Size of mp3.com-inf-20180822-212724-1gmm1-00046.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Mtime of mp3.com-inf-20180822-212724-1gmm1-00046.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Size of mp3.com-inf-20180822-212724-1gmm1-00047.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Mtime of mp3.com-inf-20180822-212724-1gmm1-00047.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Size of mp3.com-inf-20180822-212724-1gmm1-00049.warc.os.cdx.gz is missing
2018-08-27 06:00:04,857 ERRO root Mtime of mp3.com-inf-20180822-212724-1gmm1-00049.warc.os.cdx.gz is missing
2018-08-27 06:00:04,858 ERRO root Size of teslamotorsclub.com-inf-20180806-045256-azeq0-00047.warc.os.cdx.gz is missing
2018-08-27 06:00:04,858 ERRO root Mtime of teslamotorsclub.com-inf-20180806-045256-azeq0-00047.warc.os.cdx.gz is missing
2018-08-27 06:00:10,109 INFO root Processing item archiveteam_archivebot_go_20180827050002
2018-08-27 06:00:10,109 INFO root Skipping archiveteam_archivebot_go_20180827050002_archive.torrent
2018-08-27 06:00:10,109 INFO root Skipping archiveteam_archivebot_go_20180827050002_files.xml
2018-08-27 06:00:10,109 INFO root Skipping archiveteam_archivebot_go_20180827050002_meta.sqlite
2018-08-27 06:00:10,110 INFO root Skipping archiveteam_archivebot_go_20180827050002_meta.xml
2018-08-27 06:00:14,223 INFO root Processing item archiveteam_archivebot_go_www_freedominfo_org_20161228
2018-08-27 06:00:14,224 INFO root Skipping archiveteam_archivebot_go_www_freedominfo_org_20161228.cdx.idx
2018-08-27 06:00:14,224 INFO root Skipping archiveteam_archivebot_go_www_freedominfo_org_20161228_archive.torrent
2018-08-27 06:00:14,224 INFO root Skipping archiveteam_archivebot_go_www_freedominfo_org_20161228_files.xml
2018-08-27 06:00:14,224 INFO root Skipping archiveteam_archivebot_go_www_freedominfo_org_20161228_meta.sqlite
2018-08-27 06:00:14,224 INFO root Skipping archiveteam_archivebot_go_www_freedominfo_org_20161228_meta.xml
2018-08-27 06:00:17,247 INFO root Processing item astrid_archivebot_afo_wtrpg_com_20170124
2018-08-27 06:00:17,248 INFO root Skipping astrid_archivebot_afo_wtrpg_com_20170124.cdx.idx
2018-08-27 06:00:17,248 INFO root Skipping astrid_archivebot_afo_wtrpg_com_20170124_archive.torrent
2018-08-27 06:00:17,248 INFO root Skipping astrid_archivebot_afo_wtrpg_com_20170124_files.xml
2018-08-27 06:00:17,248 INFO root Skipping astrid_archivebot_afo_wtrpg_com_20170124_meta.sqlite
2018-08-27 06:00:17,248 INFO root Skipping astrid_archivebot_afo_wtrpg_com_20170124_meta.xml
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/archivebot-archives/.local/lib/python3.5/site-packages/internetarchive/session.py", line 250, in get_metadata
    resp = self.get(url, **request_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/archivebot-archives/.local/lib/python3.5/site-packages/internetarchive/session.py", line 368, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/archivebot-archives/archivebot-archives/code/update.py", line 101, in <module>
    for i in internetarchive.search_items(query, request_kwargs = {'timeout': 60}).iter_as_items(): #TODO: add max_retries
  File "/home/archivebot-archives/.local/lib/python3.5/site-packages/internetarchive/search.py", line 204, in __next__
    return self.iterator.__next__()
  File "/home/archivebot-archives/.local/lib/python3.5/site-packages/internetarchive/search.py", line 173, in _get_item_from_search_result
    return self.session.get_item(search_result['identifier'])
  File "/home/archivebot-archives/.local/lib/python3.5/site-packages/internetarchive/session.py", line 227, in get_item
    item_metadata = self.get_metadata(identifier, request_kwargs)
  File "/home/archivebot-archives/.local/lib/python3.5/site-packages/internetarchive/session.py", line 255, in get_metadata
    raise type(exc)(error_msg)
TypeError: Error retrieving metadata from https://archive.org/metadata/astrid_archivebot_pdsimage_wr_usgs_gov_20180821, unsupported operand type(s) for -=: 'Retry' and 'int'
